# Generated by Django 2.0.dev20170814182805 on 2017-08-15 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170815_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spisok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_ready', models.BooleanField(max_length=1500)),
                ('doc_TXT', models.BooleanField(max_length=1500)),
                ('doc_title', models.CharField(default='Hello', max_length=200)),
                ('doc_text', models.CharField(max_length=1500)),
                ('pub_date', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Spisok'),
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
