# Generated by Django 2.0.dev20170814182805 on 2017-08-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20170816_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spisok',
            name='doc_note',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
