# Generated by Django 2.0.dev20170814182805 on 2017-08-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20170816_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spisok',
            name='doc_note',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
