# Generated by Django 2.0.dev20170814182805 on 2017-08-16 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20170816_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='spisok',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
