# Generated by Django 2.0.dev20170814182805 on 2017-08-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_spisok_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='spisok',
            name='doc_text',
            field=models.CharField(default='Text', max_length=1500),
        ),
        migrations.AlterField(
            model_name='spisok',
            name='doc_specification',
            field=models.CharField(default='Specification', max_length=500),
        ),
    ]
