# Generated by Django 2.0.dev20170814182805 on 2017-09-06 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20170816_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spisok',
            name='pub_date',
        ),
    ]
