# Generated by Django 2.0.dev20170814182805 on 2017-09-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_titlelist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titlelist',
            old_name='doc_TXT',
            new_name='ready',
        ),
        migrations.RemoveField(
            model_name='titlelist',
            name='doc_ready',
        ),
        migrations.RemoveField(
            model_name='titlelist',
            name='doc_title',
        ),
        migrations.AddField(
            model_name='titlelist',
            name='upload',
            field=models.FileField(default=' ', upload_to='doc'),
            preserve_default=False,
        ),
    ]
