# Generated by Django 2.0.dev20170814182805 on 2017-10-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20170928_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titlelist',
            name='upload',
            field=models.ImageField(blank=True, help_text='150x150px', upload_to='images/blog/%Y/%m/%d', verbose_name='Документ'),
        ),
    ]
