# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_titlelist_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titlelist',
            name='title',
        ),
    ]
