# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_remove_titlelist_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='titlelist',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Spisok'),
            preserve_default=False,
        ),
    ]
