# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20171011_0620'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ok',
            new_name='EventTypes',
        ),
        migrations.RenameModel(
            old_name='DocList',
            new_name='LaunchOperationTypes',
        ),
    ]
