# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 07:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20171011_0638'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocSources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ready', models.BooleanField(max_length=1500)),
                ('doc_note', models.CharField(blank=True, max_length=400)),
                ('doc_text', models.CharField(default='Text', max_length=1500)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Spisok')),
            ],
        ),
        migrations.CreateModel(
            name='PayloadClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ready', models.BooleanField(max_length=1500)),
                ('doc_text', models.CharField(default='Text', max_length=1500)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Spisok')),
            ],
        ),
        migrations.AddField(
            model_name='launchoperationtypes',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='titlelist',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='eventtypes',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
