# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 13:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_auto_20171011_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docsources',
            name='title',
        ),
        migrations.RemoveField(
            model_name='eventtypes',
            name='title',
        ),
        migrations.RemoveField(
            model_name='launchoperationtypes',
            name='title',
        ),
        migrations.RemoveField(
            model_name='payloadclasses',
            name='title',
        ),
        migrations.RemoveField(
            model_name='titlelist',
            name='title',
        ),
        migrations.AlterField(
            model_name='docsources',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='docsources',
            name='doc_note',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='docsources',
            name='doc_text',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
