# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_auto_20171011_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='docsources',
            name='title',
            field=models.CharField(default='Title', max_length=200),
        ),
        migrations.AddField(
            model_name='eventtypes',
            name='title',
            field=models.CharField(default='Title', max_length=200),
        ),
        migrations.AddField(
            model_name='launchoperationtypes',
            name='title',
            field=models.CharField(default='Title', max_length=200),
        ),
        migrations.AddField(
            model_name='payloadclasses',
            name='title',
            field=models.CharField(default='Title', max_length=200),
        ),
        migrations.AddField(
            model_name='titlelist',
            name='title',
            field=models.CharField(default='Title', max_length=200),
        ),
    ]
