# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 13:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_auto_20171016_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocSources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=200)),
                ('ready', models.BooleanField(max_length=1500)),
                ('doc_note', models.CharField(max_length=400)),
                ('doc_text', models.CharField(blank=True, max_length=400, verbose_name='Текст')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='EventTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=200)),
                ('ready', models.BooleanField(max_length=1500)),
                ('doc_note', models.CharField(blank=True, max_length=400)),
                ('doc_text', models.CharField(default='Text', max_length=1500)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='LaunchOperationTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=200)),
                ('ready', models.BooleanField(max_length=1500)),
                ('doc_specification', models.CharField(default='Specification', max_length=500)),
                ('doc_note', models.CharField(blank=True, max_length=400)),
                ('doc_text', models.CharField(default='Text', max_length=1500)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='PayloadClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=200)),
                ('ready', models.BooleanField(max_length=1500)),
                ('doc_text', models.CharField(default='Text', max_length=1500)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='TitleList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=200, verbose_name='Название')),
                ('ready', models.BooleanField(max_length=1500, verbose_name='Готовность')),
                ('doc_specification', models.CharField(default='Specification', max_length=500)),
                ('doc_note', models.CharField(blank=True, max_length=400)),
                ('doc_text', models.CharField(default='Text', max_length=1500)),
                ('upload', models.ImageField(blank=True, help_text='150x150px', upload_to='images/blog/%Y/%m/%d', verbose_name='Документ')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
