# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_docsources_eventtypes_launchoperationtypes_payloadclasses_titlelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsources',
            name='doc_text',
            field=models.TextField(blank=True, max_length=400, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='eventtypes',
            name='doc_text',
            field=models.TextField(default='Text', max_length=1500),
        ),
        migrations.AlterField(
            model_name='launchoperationtypes',
            name='doc_text',
            field=models.TextField(default='Text', max_length=1500),
        ),
        migrations.AlterField(
            model_name='payloadclasses',
            name='doc_text',
            field=models.TextField(default='Text', max_length=1500),
        ),
        migrations.AlterField(
            model_name='spisok',
            name='doc_text',
            field=models.TextField(default='Text', max_length=1500),
        ),
        migrations.AlterField(
            model_name='titlelist',
            name='doc_note',
            field=models.CharField(blank=True, max_length=400, verbose_name='Заметка'),
        ),
        migrations.AlterField(
            model_name='titlelist',
            name='doc_specification',
            field=models.CharField(default='Specification', max_length=500, verbose_name='Спецификация'),
        ),
        migrations.AlterField(
            model_name='titlelist',
            name='doc_text',
            field=models.TextField(default='Text', max_length=1500, verbose_name='Текст'),
        ),
    ]
