# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_auto_20171026_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='payloadclasses',
            name='doc_note',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
